using Ledger.Api.Domain;
using Microsoft.EntityFrameworkCore;

namespace Ledger.Api.Data;

public class LedgerDbContext(DbContextOptions<LedgerDbContext> options) : DbContext(options)
{
    public DbSet<User> Users => Set<User>();

    public DbSet<Category> Categories => Set<Category>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");
            entity.HasKey(u => u.Id);

            entity.Property(u => u.Id)
                .HasColumnName("id")
                .ValueGeneratedNever(); // Ids are generated by the app, not the database.

            entity.Property(u => u.Email)
                .HasColumnName("email")
                .HasMaxLength(256)
                .IsRequired();

            entity.Property(u => u.PasswordHash)
                .HasColumnName("password_hash")
                .HasColumnType("text")
                .IsRequired();

            entity.Property(u => u.CreatedAt)
                .HasColumnName("created_at")
                .HasColumnType("timestamptz")
                .IsRequired();

            // Emails are normalised (trimmed + lowercased) before they are ever
            // written or looked up, so a plain unique index on the column gives
            // case-insensitive uniqueness without needing an expression index.
            entity.HasIndex(u => u.Email)
                .IsUnique()
                .HasDatabaseName("ix_users_email");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("categories", t => t.HasCheckConstraint(
                "ck_categories_type",
                "type IN ('income', 'expense')"));

            entity.HasKey(c => c.Id);

            entity.Property(c => c.Id)
                .HasColumnName("id")
                .ValueGeneratedNever(); // Fixed ids: later stories foreign-key to these values.

            entity.Property(c => c.Name)
                .HasColumnName("name")
                .HasMaxLength(64)
                .IsRequired();

            entity.Property(c => c.Type)
                .HasColumnName("type")
                .HasMaxLength(10)
                .IsRequired();

            entity.HasIndex(c => new { c.Name, c.Type })
                .IsUnique()
                .HasDatabaseName("ix_categories_name_type");

            entity.HasData(CategorySeedData.All);
        });
    }
}
