// <auto-generated />
using System;
using Ledger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledger.Api.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260810101235_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ledger.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name_type");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_type", "type IN ('income', 'expense')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food & Groceries",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transport",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Housing & Utilities",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Education",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Entertainment",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shopping",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Other",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Salary",
                            Type = "income"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Freelance",
                            Type = "income"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Other Income",
                            Type = "income"
                        });
                });

            modelBuilder.Entity("Ledger.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
